/*
 * generated by Xtext
 */
package org.xtext.rslilconvertors.rslil4privacy.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Rslil4privacyUiModule extends org.xtext.rslilconvertors.rslil4privacy.ui.AbstractRslil4privacyUiModule {
	public Rslil4privacyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
