/*
* generated by Xtext
*/
package org.xtext.rslilconvertors.rslil4privacy;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Rslil4privacyUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.rslilconvertors.rslil4privacy.ui.internal.Rslil4privacyActivator.getInstance().getInjector("org.xtext.rslilconvertors.rslil4privacy.Rslil4privacy");
	}
	
}
