/*
 * generated by Xtext
 */
package org.xtext.rslilconvertors.rslil4privacy.ui.contentassist

import org.xtext.rslilconvertors.rslil4privacy.ui.contentassist.AbstractRslil4privacyProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class Rslil4privacyProposalProvider extends AbstractRslil4privacyProposalProvider {
}
