/*
* generated by Xtext
*/
package org.xtext.rslilconvertors.rslil4privacy;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Rslil4privacyStandaloneSetup extends Rslil4privacyStandaloneSetupGenerated{

	public static void doSetup() {
		new Rslil4privacyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

