/*
 * generated by Xtext
 */
package org.xtext.rslilconvertors.rslil4privacy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Rslil4privacyRuntimeModule extends org.xtext.rslilconvertors.rslil4privacy.AbstractRslil4privacyRuntimeModule {

}
