/*
* generated by Xtext
*/
package org.xtext.rslilconvertors.rslil4privacy.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Rslil4privacyAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/rslilconvertors/rslil4privacy/parser/antlr/internal/InternalRslil4privacy.tokens");
	}
}
