/*
* generated by Xtext
*/
package org.xtext.rslilconvertors.rslil4privacy.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.rslilconvertors.rslil4privacy.services.Rslil4privacyGrammarAccess;

public class Rslil4privacyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Rslil4privacyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.rslilconvertors.rslil4privacy.parser.antlr.internal.InternalRslil4privacyParser createParser(XtextTokenStream stream) {
		return new org.xtext.rslilconvertors.rslil4privacy.parser.antlr.internal.InternalRslil4privacyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Policy";
	}
	
	public Rslil4privacyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Rslil4privacyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
