/*
 * generated by Xtext
 */
package org.xtext.rslilconvertors.rslil4privacy.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.rslilconvertors.rslil4privacy.ui.internal.Rslil4privacyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Rslil4privacyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Rslil4privacyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Rslil4privacyActivator.getInstance().getInjector(Rslil4privacyActivator.ORG_XTEXT_RSLILCONVERTORS_RSLIL4PRIVACY_RSLIL4PRIVACY);
	}
	
}
