/*
* generated by Xtext
*/
package org.xtext.rslilconvertors.rslil4privacy.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.rslilconvertors.rslil4privacy.services.Rslil4privacyGrammarAccess;

public class Rslil4privacyParser extends AbstractContentAssistParser {
	
	@Inject
	private Rslil4privacyGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.rslilconvertors.rslil4privacy.ui.contentassist.antlr.internal.InternalRslil4privacyParser createParser() {
		org.xtext.rslilconvertors.rslil4privacy.ui.contentassist.antlr.internal.InternalRslil4privacyParser result = new org.xtext.rslilconvertors.rslil4privacy.ui.contentassist.antlr.internal.InternalRslil4privacyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPolicyAccess().getAlternatives_4(), "rule__Policy__Alternatives_4");
					put(grammarAccess.getEnforcementAccess().getEnforcementKindAlternatives_10_0(), "rule__Enforcement__EnforcementKindAlternatives_10_0");
					put(grammarAccess.getRecipientAccess().getRecipientScopeAlternatives_11_0(), "rule__Recipient__RecipientScopeAlternatives_11_0");
					put(grammarAccess.getRecipientAccess().getRecipientTypeAlternatives_14_0(), "rule__Recipient__RecipientTypeAlternatives_14_0");
					put(grammarAccess.getPrivateDataAccess().getPrivateDataKindAlternatives_7_0(), "rule__PrivateData__PrivateDataKindAlternatives_7_0");
					put(grammarAccess.getCollectionAccess().getModalitykindAlternatives_13_0(), "rule__Collection__ModalitykindAlternatives_13_0");
					put(grammarAccess.getDisclosureAccess().getModalitykindAlternatives_16_0(), "rule__Disclosure__ModalitykindAlternatives_16_0");
					put(grammarAccess.getRetentionAccess().getModalitykindAlternatives_16_0(), "rule__Retention__ModalitykindAlternatives_16_0");
					put(grammarAccess.getUsageAccess().getModalitykindAlternatives_13_0(), "rule__Usage__ModalitykindAlternatives_13_0");
					put(grammarAccess.getInformativeAccess().getModalitykindAlternatives_13_0(), "rule__Informative__ModalitykindAlternatives_13_0");
					put(grammarAccess.getPolicyAccess().getGroup(), "rule__Policy__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getEnforcementAccess().getGroup(), "rule__Enforcement__Group__0");
					put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
					put(grammarAccess.getServiceAccess().getGroup_6(), "rule__Service__Group_6__0");
					put(grammarAccess.getServiceAccess().getGroup_7(), "rule__Service__Group_7__0");
					put(grammarAccess.getServiceAccess().getGroup_8(), "rule__Service__Group_8__0");
					put(grammarAccess.getRecipientAccess().getGroup(), "rule__Recipient__Group__0");
					put(grammarAccess.getRecipientAccess().getGroup_9(), "rule__Recipient__Group_9__0");
					put(grammarAccess.getPrivateDataAccess().getGroup(), "rule__PrivateData__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getCollectionAccess().getGroup(), "rule__Collection__Group__0");
					put(grammarAccess.getCollectionAccess().getGroup_9(), "rule__Collection__Group_9__0");
					put(grammarAccess.getCollectionAccess().getGroup_10(), "rule__Collection__Group_10__0");
					put(grammarAccess.getCollectionAccess().getGroup_11(), "rule__Collection__Group_11__0");
					put(grammarAccess.getDisclosureAccess().getGroup(), "rule__Disclosure__Group__0");
					put(grammarAccess.getDisclosureAccess().getGroup_9(), "rule__Disclosure__Group_9__0");
					put(grammarAccess.getDisclosureAccess().getGroup_10(), "rule__Disclosure__Group_10__0");
					put(grammarAccess.getDisclosureAccess().getGroup_11(), "rule__Disclosure__Group_11__0");
					put(grammarAccess.getDisclosureAccess().getGroup_12(), "rule__Disclosure__Group_12__0");
					put(grammarAccess.getDisclosureAccess().getGroup_13(), "rule__Disclosure__Group_13__0");
					put(grammarAccess.getDisclosureAccess().getGroup_14(), "rule__Disclosure__Group_14__0");
					put(grammarAccess.getRetentionAccess().getGroup(), "rule__Retention__Group__0");
					put(grammarAccess.getRetentionAccess().getGroup_12(), "rule__Retention__Group_12__0");
					put(grammarAccess.getRetentionAccess().getGroup_13(), "rule__Retention__Group_13__0");
					put(grammarAccess.getRetentionAccess().getGroup_14(), "rule__Retention__Group_14__0");
					put(grammarAccess.getUsageAccess().getGroup(), "rule__Usage__Group__0");
					put(grammarAccess.getUsageAccess().getGroup_9(), "rule__Usage__Group_9__0");
					put(grammarAccess.getUsageAccess().getGroup_10(), "rule__Usage__Group_10__0");
					put(grammarAccess.getUsageAccess().getGroup_11(), "rule__Usage__Group_11__0");
					put(grammarAccess.getInformativeAccess().getGroup(), "rule__Informative__Group__0");
					put(grammarAccess.getInformativeAccess().getGroup_9(), "rule__Informative__Group_9__0");
					put(grammarAccess.getInformativeAccess().getGroup_10(), "rule__Informative__Group_10__0");
					put(grammarAccess.getInformativeAccess().getGroup_11(), "rule__Informative__Group_11__0");
					put(grammarAccess.getPartofAccess().getGroup(), "rule__Partof__Group__0");
					put(grammarAccess.getReferToRecipientAccess().getGroup(), "rule__ReferToRecipient__Group__0");
					put(grammarAccess.getReferToRecipientSourceAccess().getGroup(), "rule__ReferToRecipientSource__Group__0");
					put(grammarAccess.getReferToRecipientTargetAccess().getGroup(), "rule__ReferToRecipientTarget__Group__0");
					put(grammarAccess.getReferToServiceAccess().getGroup(), "rule__ReferToService__Group__0");
					put(grammarAccess.getReftoPrivateDataAccess().getGroup(), "rule__ReftoPrivateData__Group__0");
					put(grammarAccess.getRefertoEnforcementAccess().getGroup(), "rule__RefertoEnforcement__Group__0");
					put(grammarAccess.getPolicyAccess().getNameAssignment_1(), "rule__Policy__NameAssignment_1");
					put(grammarAccess.getPolicyAccess().getImportelementsAssignment_3(), "rule__Policy__ImportelementsAssignment_3");
					put(grammarAccess.getPolicyAccess().getCollectionAssignment_4_0(), "rule__Policy__CollectionAssignment_4_0");
					put(grammarAccess.getPolicyAccess().getDisclosureAssignment_4_1(), "rule__Policy__DisclosureAssignment_4_1");
					put(grammarAccess.getPolicyAccess().getRetentionAssignment_4_2(), "rule__Policy__RetentionAssignment_4_2");
					put(grammarAccess.getPolicyAccess().getUsageAssignment_4_3(), "rule__Policy__UsageAssignment_4_3");
					put(grammarAccess.getPolicyAccess().getInformativeAssignment_4_4(), "rule__Policy__InformativeAssignment_4_4");
					put(grammarAccess.getPolicyAccess().getPrivateDataAssignment_5(), "rule__Policy__PrivateDataAssignment_5");
					put(grammarAccess.getPolicyAccess().getRecipientAssignment_6(), "rule__Policy__RecipientAssignment_6");
					put(grammarAccess.getPolicyAccess().getServiceAssignment_7(), "rule__Policy__ServiceAssignment_7");
					put(grammarAccess.getPolicyAccess().getEnforcementAssignment_8(), "rule__Policy__EnforcementAssignment_8");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getEnforcementAccess().getNameAssignment_1(), "rule__Enforcement__NameAssignment_1");
					put(grammarAccess.getEnforcementAccess().getEnforcementNameAssignment_4(), "rule__Enforcement__EnforcementNameAssignment_4");
					put(grammarAccess.getEnforcementAccess().getEnforcementDescriptionAssignment_7(), "rule__Enforcement__EnforcementDescriptionAssignment_7");
					put(grammarAccess.getEnforcementAccess().getEnforcementKindAssignment_10(), "rule__Enforcement__EnforcementKindAssignment_10");
					put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
					put(grammarAccess.getServiceAccess().getServicenameAssignment_4(), "rule__Service__ServicenameAssignment_4");
					put(grammarAccess.getServiceAccess().getDescriptionAssignment_6_1(), "rule__Service__DescriptionAssignment_6_1");
					put(grammarAccess.getServiceAccess().getReftoPrivateDataAssignment_7_1(), "rule__Service__ReftoPrivateDataAssignment_7_1");
					put(grammarAccess.getServiceAccess().getRefertoserviceAssignment_8_1(), "rule__Service__RefertoserviceAssignment_8_1");
					put(grammarAccess.getRecipientAccess().getNameAssignment_1(), "rule__Recipient__NameAssignment_1");
					put(grammarAccess.getRecipientAccess().getRecipientnameAssignment_4(), "rule__Recipient__RecipientnameAssignment_4");
					put(grammarAccess.getRecipientAccess().getRecipientDescriptionAssignment_7(), "rule__Recipient__RecipientDescriptionAssignment_7");
					put(grammarAccess.getRecipientAccess().getPartofAssignment_9_1(), "rule__Recipient__PartofAssignment_9_1");
					put(grammarAccess.getRecipientAccess().getRecipientScopeAssignment_11(), "rule__Recipient__RecipientScopeAssignment_11");
					put(grammarAccess.getRecipientAccess().getRecipientTypeAssignment_14(), "rule__Recipient__RecipientTypeAssignment_14");
					put(grammarAccess.getPrivateDataAccess().getNameAssignment_1(), "rule__PrivateData__NameAssignment_1");
					put(grammarAccess.getPrivateDataAccess().getPrivatedataAssignment_4(), "rule__PrivateData__PrivatedataAssignment_4");
					put(grammarAccess.getPrivateDataAccess().getPrivateDataKindAssignment_7(), "rule__PrivateData__PrivateDataKindAssignment_7");
					put(grammarAccess.getPrivateDataAccess().getAttributeAssignment_9(), "rule__PrivateData__AttributeAssignment_9");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getAttributeNameAssignment_3(), "rule__Attribute__AttributeNameAssignment_3");
					put(grammarAccess.getCollectionAccess().getNameAssignment_1(), "rule__Collection__NameAssignment_1");
					put(grammarAccess.getCollectionAccess().getCollectiondescriptionAssignment_4(), "rule__Collection__CollectiondescriptionAssignment_4");
					put(grammarAccess.getCollectionAccess().getCollectionconditionAssignment_7(), "rule__Collection__CollectionconditionAssignment_7");
					put(grammarAccess.getCollectionAccess().getReftoPrivateDataAssignment_9_1(), "rule__Collection__ReftoPrivateDataAssignment_9_1");
					put(grammarAccess.getCollectionAccess().getRefertoserviceAssignment_10_1(), "rule__Collection__RefertoserviceAssignment_10_1");
					put(grammarAccess.getCollectionAccess().getRefertoEnforcementAssignment_11_1(), "rule__Collection__RefertoEnforcementAssignment_11_1");
					put(grammarAccess.getCollectionAccess().getModalitykindAssignment_13(), "rule__Collection__ModalitykindAssignment_13");
					put(grammarAccess.getDisclosureAccess().getNameAssignment_1(), "rule__Disclosure__NameAssignment_1");
					put(grammarAccess.getDisclosureAccess().getDidescriptionAssignment_4(), "rule__Disclosure__DidescriptionAssignment_4");
					put(grammarAccess.getDisclosureAccess().getDisconditionAssignment_7(), "rule__Disclosure__DisconditionAssignment_7");
					put(grammarAccess.getDisclosureAccess().getReferToRecipientAssignment_9_1(), "rule__Disclosure__ReferToRecipientAssignment_9_1");
					put(grammarAccess.getDisclosureAccess().getReferToRecipientsourceAssignment_10_1(), "rule__Disclosure__ReferToRecipientsourceAssignment_10_1");
					put(grammarAccess.getDisclosureAccess().getReferToRecipienttargetAssignment_11_1(), "rule__Disclosure__ReferToRecipienttargetAssignment_11_1");
					put(grammarAccess.getDisclosureAccess().getReftoPrivateDataAssignment_12_1(), "rule__Disclosure__ReftoPrivateDataAssignment_12_1");
					put(grammarAccess.getDisclosureAccess().getRefertoserviceAssignment_13_1(), "rule__Disclosure__RefertoserviceAssignment_13_1");
					put(grammarAccess.getDisclosureAccess().getRefertoEnforcementAssignment_14_1(), "rule__Disclosure__RefertoEnforcementAssignment_14_1");
					put(grammarAccess.getDisclosureAccess().getModalitykindAssignment_16(), "rule__Disclosure__ModalitykindAssignment_16");
					put(grammarAccess.getRetentionAccess().getNameAssignment_1(), "rule__Retention__NameAssignment_1");
					put(grammarAccess.getRetentionAccess().getRetentiondescriptionAssignment_4(), "rule__Retention__RetentiondescriptionAssignment_4");
					put(grammarAccess.getRetentionAccess().getRetentionconditionAssignment_7(), "rule__Retention__RetentionconditionAssignment_7");
					put(grammarAccess.getRetentionAccess().getPeriodAssignment_10(), "rule__Retention__PeriodAssignment_10");
					put(grammarAccess.getRetentionAccess().getReftoPrivateDataAssignment_12_1(), "rule__Retention__ReftoPrivateDataAssignment_12_1");
					put(grammarAccess.getRetentionAccess().getRefertoserviceAssignment_13_1(), "rule__Retention__RefertoserviceAssignment_13_1");
					put(grammarAccess.getRetentionAccess().getRefertoEnforcementAssignment_14_1(), "rule__Retention__RefertoEnforcementAssignment_14_1");
					put(grammarAccess.getRetentionAccess().getModalitykindAssignment_16(), "rule__Retention__ModalitykindAssignment_16");
					put(grammarAccess.getUsageAccess().getNameAssignment_1(), "rule__Usage__NameAssignment_1");
					put(grammarAccess.getUsageAccess().getUsagedescriptionAssignment_4(), "rule__Usage__UsagedescriptionAssignment_4");
					put(grammarAccess.getUsageAccess().getUsageconditionAssignment_7(), "rule__Usage__UsageconditionAssignment_7");
					put(grammarAccess.getUsageAccess().getReftoPrivateDataAssignment_9_1(), "rule__Usage__ReftoPrivateDataAssignment_9_1");
					put(grammarAccess.getUsageAccess().getRefertoserviceAssignment_10_1(), "rule__Usage__RefertoserviceAssignment_10_1");
					put(grammarAccess.getUsageAccess().getRefertoEnforcementAssignment_11_1(), "rule__Usage__RefertoEnforcementAssignment_11_1");
					put(grammarAccess.getUsageAccess().getModalitykindAssignment_13(), "rule__Usage__ModalitykindAssignment_13");
					put(grammarAccess.getInformativeAccess().getNameAssignment_1(), "rule__Informative__NameAssignment_1");
					put(grammarAccess.getInformativeAccess().getInfdescriptionAssignment_4(), "rule__Informative__InfdescriptionAssignment_4");
					put(grammarAccess.getInformativeAccess().getInfconditionAssignment_7(), "rule__Informative__InfconditionAssignment_7");
					put(grammarAccess.getInformativeAccess().getReftoPrivateDataAssignment_9_1(), "rule__Informative__ReftoPrivateDataAssignment_9_1");
					put(grammarAccess.getInformativeAccess().getRefertoserviceAssignment_10_1(), "rule__Informative__RefertoserviceAssignment_10_1");
					put(grammarAccess.getInformativeAccess().getRefertoEnforcementAssignment_11_1(), "rule__Informative__RefertoEnforcementAssignment_11_1");
					put(grammarAccess.getInformativeAccess().getModalitykindAssignment_13(), "rule__Informative__ModalitykindAssignment_13");
					put(grammarAccess.getPartofAccess().getPartofAssignment_0(), "rule__Partof__PartofAssignment_0");
					put(grammarAccess.getReferToRecipientAccess().getRefertoreAssignment_0(), "rule__ReferToRecipient__RefertoreAssignment_0");
					put(grammarAccess.getReferToRecipientSourceAccess().getRefertoreAssignment_0(), "rule__ReferToRecipientSource__RefertoreAssignment_0");
					put(grammarAccess.getReferToRecipientTargetAccess().getRefertoreAssignment_0(), "rule__ReferToRecipientTarget__RefertoreAssignment_0");
					put(grammarAccess.getReferToServiceAccess().getRefertoseAssignment_0(), "rule__ReferToService__RefertoseAssignment_0");
					put(grammarAccess.getReftoPrivateDataAccess().getRefprAssignment_0(), "rule__ReftoPrivateData__RefprAssignment_0");
					put(grammarAccess.getRefertoEnforcementAccess().getRefenAssignment_0(), "rule__RefertoEnforcement__RefenAssignment_0");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.rslilconvertors.rslil4privacy.ui.contentassist.antlr.internal.InternalRslil4privacyParser typedParser = (org.xtext.rslilconvertors.rslil4privacy.ui.contentassist.antlr.internal.InternalRslil4privacyParser) parser;
			typedParser.entryRulePolicy();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Rslil4privacyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Rslil4privacyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
