/*
 * generated by Xtext
 */
package org.xtext.rslilconvertors.rslil4privacy.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRslil4privacyValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.xtext.rslilconvertors.rslil4privacy.rslil4privacy.Rslil4privacyPackage.eINSTANCE);
		return result;
	}
}
